#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server:
PATH_TO_SSH_KEY=$4
PATH_TO_FILE=$1
USERNAME=$3
IP=$2

if [ $# -le 3 ]
  then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -gt 3 ]
  then
    scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
else
    scp -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"
fi