#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another
sudo apt-get update
sudo apt-get install -y nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
new_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$new_str/" /etc/nginx/sites-enabled/default
sudo service nginx restart
