#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$str/" /etc/nginx/sites-enabled/default
sudo service nginx restart
