#!/usr/bin/env bash
# Bash script configures a new Ubuntu machine to match the task requirements
sudo apt-get update
sudo apt-get -y install nginx
new_header="\n\tadd_header X-Served-By '$HOSTNAME';"

sudo sed -i "s/listen \[::\]:80 default_server;/&$new_header/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
