#!/usr/bin/env bash
# configuring HAproxy to send traffic to web-01 and web-02, among other rqurmnts
# installing haproxy in the newst version
sudo apt-get -y update
sudo apt-get -y install haproxy
# enable proxy to be started by the init script
# by echo cmnd redirected to haproxy file
sudo echo "ENABLED=1" | sudo tee /etc/default/haproxy
# configure the template for load balancer on the haproxy.cfg file
sudo echo "
frontend http_front
	  bind *:80
	   mode http
	    default_backend http_back
backend http_back
	balance roundrobin
	server 1792-web-01 35.227.50.149:80 check
	server 1792-web-02 34.73.221.231:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
