#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

while x=":" read -r USERNAME PASSWORD ID GROUP_ID INFO HOME_DIRECTORY SHELL
do
echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY \
and rides $SHELL. $ID's place is protected by the passcode $PASSWORD, more info \
about the user here: $INFO"
done < /etc/passwd