#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i="0"

while [ "$i" -lt 13 ]
do
	echo "Hour: $i"
	x="1"
	while [ "$x" -lt 60 ]
	do
		echo "$x"
		x=$((x+1))
	done
	i=$((i+1))
done
